AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/DotPosition:
  EnforcedStyle: leading

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 15
